language: c++
compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install -qq libzmq3-dev libprotobuf-dev protobuf-compiler cmake libboost-all-dev liblog4cxx10-dev valgrind
    - wget https://raw.github.com/zeromq/cppzmq/master/zmq.hpp -O ./include/zmq.hpp
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
    - mkdir -p ./build
    - cd ./build && cmake .. && make

after_success:
    - cd ./test && ctest ; cd ..
    - make ExperimentalMemCheck
    - sed -n -e '/LEAK SUMMARY:/,+8p' -e '/^Test\|Test\(ing\)\?: /p' Testing/Temporary/LastDynamicAnalysis_*.log

